### ISSUE TITLE
Why not using an OpenTripPlanner image from Docker Hub?

### ISSUE THREAD

**Issue by ValorNaram** [trufi-association/trufi-server#7]
@SamuelRioTz Why not using an OpenTripPlanner image from Docker Hub?

https://github.com/trufi-association/trufi-server/blob/91ea0b50b802cdfb6d394af4d02158805e646a11/extensions/otp/docker-compose.yml#L4

**Comment by SamuelRioTz** [comment]
I did not find an official image from OpenTripPlanner

**Comment by SamuelRioTz** [comment]
no one takes care about that one, last update was 6 years ago

**Comment by ValorNaram** [comment]
What about https://hub.docker.com/r/mfdz/opentripplanner . We use it on the current backend:

```yml
opentripplanner-bikeapphamburg:
    image: mfdz/opentripplanner:latest
    command: --load graph
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "/srv/trufi/bikeapphamburg/graph:/opt/opentripplanner/graph"
    #  - "/srv/trufi/graphs.bikeapphamburg/hamburg-hvv:/opt/opentripplanner/graph"
    #  - "/srv/trufi/logs.bikeapphamburg:/tmp"
      - "/srv/trufi/bikeapphamburg/logs:/tmp"
      - "/etc/timezone:/etc/timezone:ro" # needed for correct time in the docker OTP instance
      - "/etc/localtime:/etc/localtime:ro" # needed for correct time in the docker OTP instance
      # todo log files
    restart: unless-stopped
    networks:
      - frontend
```

We can use a modified version of it.
